version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - ./mvnw clean install
  build:
    commands:
      - ./mvnw package
artifacts:
  files: target/*.jar
  discard-paths: yes
